name: 'Run Unit Tests'
 
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
 
jobs:
  run-network-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'

      - name: Run Unit Tests
        run: |
          cd crypto
          go test
          cd ..

          cd definition
          go test
          cd ..

          cd Gen
          go test
          cd ..
          
          cd gossiper 
          go test 
          cd ..

          cd Logger 
          go test 
          cd ..

          cd monitor 
          go test 
          cd ..

